import { SectionConfig, SectionType, ThemeConfig } from "@/lib/repo/theme";

export interface SectionTemplateDefinition {
  type: SectionType;
  name: string;
  category: "Destaques" | "Produtos & Coleções" | "Mídia & Imagem" | "Texto & Prova Social" | "Avançado";
  description: string;
  iconName: string;
  createDefault: () => SectionConfig;
}

export const SECTION_TEMPLATES: SectionTemplateDefinition[] = [
  {
    type: "hero_banner",
    name: "Banner Principal (Hero)",
    category: "Destaques",
    description: "Banner de grande impacto com título, chamada para ação, destaques e fundo moderno.",
    iconName: "LayoutTemplate",
    createDefault: () => ({
      id: `sec-hero-${Date.now()}`,
      type: "hero_banner",
      name: "Banner Principal (Hero)",
      enabled: true,
      settings: {
        eyebrow: "✨ Nova Coleção 2026 • Shopify Experience",
        title: "Os melhores produtos com a qualidade que você confia.",
        titleHighlight: "confia",
        subtitle: "Explore milhares de itens selecionados a dedo com entrega rápida e garantia total de 30 dias.",
        primaryButtonText: "Explorar Catálogo",
        primaryButtonUrl: "/produtos",
        secondaryButtonText: "Ver Ofertas",
        secondaryButtonUrl: "/produtos",
        styleVariant: "dark_glow",
        stat1Number: "+10k",
        stat1Label: "Pedidos Entregues",
        stat2Number: "4.9 ★",
        stat2Label: "Avaliação Média",
        stat3Number: "100%",
        stat3Label: "Checkout Seguro",
        imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=80",
        bannerHeight: "500px",
        overlayOpacity: "0.3",
      },
    }),
  },
  {
    type: "image_banner",
    name: "Banner de Imagem (Sem Texto / Imagem Única)",
    category: "Mídia & Imagem",
    description: "Banner puramente visual para exibir campanhas, fotos de produtos ou layouts de alta definição sem texto.",
    iconName: "Image",
    createDefault: () => ({
      id: `sec-img-banner-${Date.now()}`,
      type: "image_banner",
      name: "Banner de Imagem",
      enabled: true,
      settings: {
        imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=80",
        bannerHeight: "450px",
        bannerLink: "/produtos",
        aspectRatio: "adapt",
        borderRadius: "rounded-3xl",
      },
    }),
  },
  {
    type: "marquee_ticker",
    name: "Faixa de Destaques (Marquee)",
    category: "Destaques",
    description: "Faixa com rolagem contínua de anúncios rápidos e avisos promocionais.",
    iconName: "Zap",
    createDefault: () => ({
      id: `sec-marquee-${Date.now()}`,
      type: "marquee_ticker",
      name: "Faixa de Destaques (Marquee)",
      enabled: true,
      settings: {
        speed: "normal",
        bgColor: "#008060",
        textColor: "#ffffff",
        items: [
          "🚀 ENVIO RÁPIDO PARA TODO BRASIL",
          "🔒 PAGAMENTO 100% SEGURO",
          "💳 ATÉ 12X SEM JUROS",
          "⭐ MAIS DE 5.000 CLIENTES SATISFEITOS",
        ],
      },
    }),
  },
  {
    type: "features_bar",
    name: "Diferenciais da Loja",
    category: "Destaques",
    description: "Grade com 4 pilares de confiança (Frete Grátis, Parcelamento, Suporte, Garantia).",
    iconName: "ShieldCheck",
    createDefault: () => ({
      id: `sec-features-${Date.now()}`,
      type: "features_bar",
      name: "Diferenciais da Loja",
      enabled: true,
      settings: {
        f1Title: "Frete Grátis",
        f1Desc: "Em compras acima de R$ 199 para todo o Brasil",
        f2Title: "Até 12x Sem Juros",
        f2Desc: "Ou 5% de desconto à vista via Pix",
        f3Title: "Compra Garantida",
        f3Desc: "30 dias para trocas e devoluções grátis",
        f4Title: "Suporte 24/7",
        f4Desc: "Atendimento humanizado em tempo real",
      },
    }),
  },
  {
    type: "featured_products",
    name: "Produtos em Destaque",
    category: "Produtos & Coleções",
    description: "Grade dinâmica de produtos selecionados, mais vendidos ou filtrados por categoria.",
    iconName: "ShoppingBag",
    createDefault: () => ({
      id: `sec-featured-products-${Date.now()}`,
      type: "featured_products",
      name: "Produtos em Destaque",
      enabled: true,
      settings: {
        eyebrow: "Destaques da Loja",
        title: "Mais Vendidos da Semana",
        limit: 8,
        sort: "price_desc",
        categorySlug: "all",
      },
    }),
  },
  {
    type: "featured_collections",
    name: "Coleções em Destaque",
    category: "Produtos & Coleções",
    description: "Lista visual de coleções e categorias para navegação dos clientes.",
    iconName: "Grid",
    createDefault: () => ({
      id: `sec-collections-${Date.now()}`,
      type: "featured_collections",
      name: "Coleções em Destaque",
      enabled: true,
      settings: {
        title: "Coleções em Destaque",
        subtitle: "Navegue pelas principais categorias da loja",
        limit: 5,
        layout: "grid",
      },
    }),
  },
  {
    type: "new_arrivals",
    name: "Novidades Recentes",
    category: "Produtos & Coleções",
    description: "Exibe os produtos mais recentes cadastrados no catálogo da loja.",
    iconName: "Sparkles",
    createDefault: () => ({
      id: `sec-new-arrivals-${Date.now()}`,
      type: "new_arrivals",
      name: "Novidades Recentes",
      enabled: true,
      settings: {
        title: "Novidades Recentes",
        subtitle: "Últimos lançamentos adicionados ao nosso catálogo",
        limit: 4,
      },
    }),
  },
  {
    type: "promo_banner",
    name: "Banner Promocional",
    category: "Mídia & Imagem",
    description: "Seção de alta conversão com cupom de desconto em destaque e botão de compra.",
    iconName: "Tag",
    createDefault: () => ({
      id: `sec-promo-${Date.now()}`,
      type: "promo_banner",
      name: "Banner Promocional",
      enabled: true,
      settings: {
        badge: "Promoção por Tempo Limitado ⚡",
        heading: "Até 40% OFF nos produtos mais desejados",
        description: "Use o cupom PRIMEIRACOMPRA no checkout para garantir 10% de desconto adicional.",
        couponCode: "PRIMEIRACOMPRA",
        buttonText: "Aproveitar Ofertas",
        buttonUrl: "/produtos",
        themeStyle: "dark",
      },
    }),
  },
  {
    type: "image_with_text",
    name: "Imagem com Texto",
    category: "Mídia & Imagem",
    description: "Apresentação institucional com imagem em destaque, benefícios e botão de ação.",
    iconName: "Image",
    createDefault: () => ({
      id: `sec-image-with-text-${Date.now()}`,
      type: "image_with_text",
      name: "Imagem com Texto",
      enabled: true,
      settings: {
        badge: "Qualidade Garantida",
        heading: "A melhor experiência de compra direto na sua casa",
        bodyText: "Nossos produtos passam por um rigoroso controle de qualidade para garantir durabilidade e sofisticação.",
        buttonText: "Conhecer Mais",
        buttonUrl: "/produtos",
        imagePosition: "right",
        item1: "Produtos 100% originais com nota fiscal",
        item2: "Embalagem premium reforçada e discreta",
        item3: "Rastreamento em tempo real via WhatsApp e E-mail",
      },
    }),
  },
  {
    type: "video_banner",
    name: "Banner de Vídeo / Mídia",
    category: "Mídia & Imagem",
    description: "Apresentação de vídeo com sobreposição de texto e botão de chamada para ação.",
    iconName: "Video",
    createDefault: () => ({
      id: `sec-video-${Date.now()}`,
      type: "video_banner",
      name: "Banner de Vídeo",
      enabled: true,
      settings: {
        heading: "Conheça o processo de fabricação artesanal",
        subtitle: "Veja como cuidamos de cada detalhe antes do envio.",
        buttonText: "Ver Produtos",
        buttonUrl: "/produtos",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
    }),
  },
  {
    type: "testimonials",
    name: "Depoimentos de Clientes",
    category: "Texto & Prova Social",
    description: "Avaliações e depoimentos reais com classificação por estrelas e foto de clientes.",
    iconName: "MessageSquare",
    createDefault: () => ({
      id: `sec-testimonials-${Date.now()}`,
      type: "testimonials",
      name: "Depoimentos de Clientes",
      enabled: true,
      settings: {
        title: "O que nossos clientes dizem",
        subtitle: "Mais de 10.000 clientes satisfeitos em todo o Brasil",
      },
      blocks: [
        {
          id: `t-${Date.now()}-1`,
          type: "testimonial_item",
          settings: {
            author: "Mariana Silva",
            role: "São Paulo, SP",
            rating: 5,
            comment: "Excelente atendimento! O produto chegou em 2 dias bem embalado e superou minhas expectativas.",
          },
        },
        {
          id: `t-${Date.now()}-2`,
          type: "testimonial_item",
          settings: {
            author: "Carlos Eduardo",
            role: "Belo Horizonte, MG",
            rating: 5,
            comment: "Site super fluido, checkout rápido e transparência total no rastreio. Recomendo muito!",
          },
        },
      ],
    }),
  },
  {
    type: "faq_accordion",
    name: "Perguntas Frequentes (FAQ)",
    category: "Texto & Prova Social",
    description: "Lista de perguntas e respostas em acordeão expansível para tirar dúvidas comuns.",
    iconName: "HelpCircle",
    createDefault: () => ({
      id: `sec-faq-${Date.now()}`,
      type: "faq_accordion",
      name: "Perguntas Frequentes (FAQ)",
      enabled: true,
      settings: {
        title: "Dúvidas Frequentes",
        subtitle: "Tudo o que você precisa saber antes de comprar",
      },
      blocks: [
        {
          id: `faq-${Date.now()}-1`,
          type: "faq_item",
          settings: {
            question: "Qual o prazo de entrega dos pedidos?",
            answer: "O prazo varia de 2 a 7 dias úteis dependendo da sua região com rastreamento completo.",
          },
        },
        {
          id: `faq-${Date.now()}-2`,
          type: "faq_item",
          settings: {
            question: "Como funciona a garantia de 30 dias?",
            answer: "Caso não goste ou queira trocar, garantimos a devolução 100% gratuita dentro de 30 dias.",
          },
        },
      ],
    }),
  },
  {
    type: "multi_column",
    name: "Colunas Informativas",
    category: "Texto & Prova Social",
    description: "Grade de 3 a 4 colunas com ícones e textos para explicar vantagens ou etapas.",
    iconName: "Columns",
    createDefault: () => ({
      id: `sec-multi-col-${Date.now()}`,
      type: "multi_column",
      name: "Colunas Informativas",
      enabled: true,
      settings: {
        title: "Por que escolher a nossa loja?",
        subtitle: "Garantias e compromisso com você",
      },
      blocks: [
        {
          id: `col-${Date.now()}-1`,
          type: "column_item",
          settings: {
            icon: "Truck",
            title: "Logística Expressa",
            text: "Centros de distribuição estratégicos para entregas ágeis em qualquer estado.",
          },
        },
        {
          id: `col-${Date.now()}-2`,
          type: "column_item",
          settings: {
            icon: "Shield",
            title: "Garantia Estendida",
            text: "Todos os produtos contam com proteção e suporte pós-venda dedicado.",
          },
        },
        {
          id: `col-${Date.now()}-3`,
          type: "column_item",
          settings: {
            icon: "HeartHandshake",
            title: "Atendimento Humanizado",
            text: "Equipe especializada pronta para tirar dúvidas a qualquer momento.",
          },
        },
      ],
    }),
  },
  {
    type: "newsletter",
    name: "Captura de E-mails (Newsletter)",
    category: "Avançado",
    description: "Formulário de inscrição para fidelização e envio de cupons de desconto.",
    iconName: "Mail",
    createDefault: () => ({
      id: `sec-newsletter-${Date.now()}`,
      type: "newsletter",
      name: "Captura de E-mails (Newsletter)",
      enabled: true,
      settings: {
        heading: "Fique por dentro das ofertas exclusivas",
        text: "Cadastre seu e-mail e receba cupons de desconto VIP e lançamentos em primeira mão.",
        placeholder: "Digite seu melhor e-mail...",
        buttonText: "Cadastrar",
      },
    }),
  },
  {
    type: "custom_html_liquid",
    name: "HTML / Liquid Customizado",
    category: "Avançado",
    description: "Insira blocos de código HTML, iframes ou scripts de terceiros com total liberdade.",
    iconName: "Code",
    createDefault: () => ({
      id: `sec-html-${Date.now()}`,
      type: "custom_html_liquid",
      name: "HTML / Liquid Customizado",
      enabled: true,
      settings: {
        heading: "Conteúdo Personalizado",
        htmlCode: `<div class="p-6 text-center bg-brand-50 border border-brand-200 rounded-2xl">
  <h3 class="text-xl font-bold text-brand-900">Bloco Customizado HTML</h3>
  <p class="text-sm text-brand-700 mt-2">Você pode personalizar este elemento como desejar no editor de temas.</p>
</div>`,
      },
    }),
  },
];

export interface ThemePresetDefinition {
  id: string;
  name: string;
  badge: string;
  description: string;
  primaryColor: string;
  accentColor: string;
  config: ThemeConfig;
}

export const THEME_PRESETS: ThemePresetDefinition[] = [
  {
    id: "farfetch",
    name: "Farfetch España",
    badge: "Alta Moda & Gallery",
    description: "White-cube fashion gallery inspirada na Farfetch España: ausência total de ornamentos cromáticos, tipografia geométrica pura (Farfetch Basis / Inter), grids arquitetônicos 3 e 4 colunas, raio de borda zero (0px) e fotografia editorial em destaque absoluto.",
    primaryColor: "#222222",
    accentColor: "#727272",
    config: {
      id: "farfetch",
      name: "FARFETCH España - White-Cube Gallery",
      version: "15.0.0",
      updatedAt: new Date().toISOString(),
      colors: {
        primary: "#222222",
        primaryHover: "#000000",
        accent: "#727272",
        background: "#ffffff",
        surface: "#ffffff",
        textMain: "#222222",
        textMuted: "#727272",
        border: "#e6e6e6",
      },
      typography: {
        headingFont: "Inter",
        bodyFont: "Inter",
        baseFontSize: "15px",
      },
      layout: {
        containerWidth: "1280px",
        borderRadius: "rounded-none",
        buttonRadius: "rounded-none",
        cardShadow: "none",
      },
      announcement: {
        enabled: true,
        text: "ENVÍOS Y DEVOLUCIONES GRATUITAS EN TODOS LOS PEDIDOS | ALTA MODA INTERNACIONAL",
        badgeText: "FARFETCH",
        linkText: "Descubre Más",
        linkUrl: "/produtos",
        bgStyle: "brand",
        showSecurityBadge: false,
      },
      header: {
        sticky: true,
        logoText: "FARFETCH",
        logoBadge: "ESPAÑA",
        searchPlaceholder: "Buscar piezas, diseñadores y novedades...",
        showCartBadge: true,
        showAccountLink: true,
      },
      social: {
        instagram: "https://instagram.com/farfetch",
        tiktok: "https://tiktok.com/@farfetch",
      },
      footer: {
        copyright: "© 2026 FARFETCH UK Limited. Todos los derechos reservados.",
        tagline: "El destino global del lujo moderno. Moda de autor y colecciones exclusivas.",
        showPaymentBadges: true,
        showNewsletter: true,
        columns: [
          {
            id: "col-1",
            title: "Comprar",
            links: [
              { label: "Novedades Mujer", href: "/produtos?categoria=moda" },
              { label: "Novedades Hombre", href: "/produtos?categoria=moda" },
              { label: "Bolsos & Zapatos", href: "/produtos?categoria=moda" },
              { label: "Diseñadores Exclusivos", href: "/produtos" },
            ],
          },
          {
            id: "col-2",
            title: "Atención al Cliente",
            links: [
              { label: "Ayuda y Preguntas Frecuentes", href: "#" },
              { label: "Seguimiento de Pedidos", href: "/conta" },
              { label: "Devoluciones y Reembolsos", href: "#" },
              { label: "Términos y Condiciones", href: "#" },
            ],
          },
          {
            id: "col-3",
            title: "Sobre Farfetch",
            links: [
              { label: "Acerca de Nosotros", href: "#" },
              { label: "Farfetch Partner Boutiques", href: "#" },
              { label: "Sostenibilidad", href: "#" },
              { label: "Prensa", href: "#" },
            ],
          },
        ],
      },
      customCss: "",
      sections: [
        {
          id: "sec-farfetch-hero",
          type: "hero_banner",
          name: "Hero Editorial Farfetch",
          enabled: true,
          settings: {
            eyebrow: "",
            title: "Colección Primavera / Verano 2026",
            titleHighlight: "2026",
            subtitle: "Descubre la nueva selección de diseñadores internacionales con una estética arquitectónica y depurada.",
            primaryButtonText: "Comprar Mujer",
            primaryButtonUrl: "/produtos?categoria=moda",
            secondaryButtonText: "Comprar Hombre",
            secondaryButtonUrl: "/produtos?categoria=moda",
            styleVariant: "clean_light",
            imageUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1600&q=80",
            bannerHeight: "560px",
            stat1Number: "1.400+",
            stat1Label: "Marcas de Lujo",
            stat2Number: "190",
            stat2Label: "Países de Envío",
            stat3Number: "100%",
            stat3Label: "Autenticidad Garantizada",
          },
        },
        {
          id: "sec-farfetch-collections",
          type: "featured_collections",
          name: "Categorías Editoriales (Mujer · Hombre · Infantil)",
          enabled: true,
          settings: {
            title: "Elige una sección",
            subtitle: "Explora la moda a través de nuestras galerías exclusivas",
            limit: 5,
            layout: "grid",
          },
        },
        {
          id: "sec-farfetch-products",
          type: "featured_products",
          name: "Novedades & Piezas de Autor",
          enabled: true,
          settings: {
            eyebrow: "",
            title: "Moda de Vanguardia",
            limit: 8,
            sort: "price_desc",
            categorySlug: "all",
          },
        },
        {
          id: "sec-farfetch-image-with-text",
          type: "image_with_text",
          name: "Manifiesto Editorial",
          enabled: true,
          settings: {
            badge: "VISIÓN EDITORIAL",
            heading: "La intersección entre arte, arquitectura y alta costura",
            bodyText: "Una curaduría minuciosa donde las prendas y las siluetas cobran todo el protagonismo. Espacios en blanco puro que enmarcan la esencia del diseño contemporáneo.",
            buttonText: "Explorar Diseñadores",
            buttonUrl: "/produtos",
            imagePosition: "right",
            item1: "Curaduría directa de las mejores boutiques del mundo",
            item2: "Embalaje ecológico y discreto con entrega express",
            item3: "Servicio de conserjería y personal shopper",
          },
        },
        {
          id: "sec-farfetch-faq",
          type: "faq_accordion",
          name: "Servicio al Cliente & Políticas",
          enabled: true,
          settings: {
            title: "Servicios y Preguntas Frecuentes",
            subtitle: "Todo sobre envíos internacionales, devoluciones y autenticidad",
          },
          blocks: [
            {
              id: "faq-f1",
              type: "faq_item",
              settings: {
                question: "¿Cómo funciona el envío express internacional?",
                answer: "Entregamos en 2 a 4 días hábiles mediante DHL Express y FedEx con seguimiento en tiempo real y seguro total incluido.",
              },
            },
            {
              id: "faq-f2",
              type: "faq_item",
              settings: {
                question: "¿Las piezas son 100% auténticas?",
                answer: "Absolutamente. Todos los artículos provienen directamente de las casas de moda oficiales o de nuestra red global de boutiques asociadas verificadas.",
              },
            },
            {
              id: "faq-f3",
              type: "faq_item",
              settings: {
                question: "¿Cuál es la política de devoluciones gratuitas?",
                answer: "Ofrecemos recogida a domicilio gratuita y 14 días para devolver cualquier artículo sin costo alguno.",
              },
            },
          ],
        },
        {
          id: "sec-farfetch-newsletter",
          type: "newsletter",
          name: "Suscripción Farfetch Privé",
          enabled: true,
          settings: {
            heading: "Únete al universo Farfetch",
            text: "Recibe invitaciones exclusivas a ventas privadas, lanzamientos anticipados de colecciones y novedades de alta moda.",
            placeholder: "Introduce tu correo electrónico...",
            buttonText: "Suscribirse",
          },
        },
      ],
    },
  },
  {
    id: "dawn",
    name: "Dawn 15.0",
    badge: "Padrão Shopify",
    description: "Design clássico oficial da Shopify com verde elegante, navegação limpa e alta taxa de conversão.",
    primaryColor: "#008060",
    accentColor: "#10b981",
    config: {
      id: "dawn",
      name: "Dawn 15.0 - SensaShop",
      version: "15.0.0",
      updatedAt: new Date().toISOString(),
      colors: {
        primary: "#008060",
        primaryHover: "#006e52",
        accent: "#10b981",
        background: "#f6f6f7",
        surface: "#ffffff",
        textMain: "#1a1c1d",
        textMuted: "#6d7175",
        border: "#e1e3e5",
      },
      typography: {
        headingFont: "Plus Jakarta Sans",
        bodyFont: "Inter",
        baseFontSize: "16px",
      },
      layout: {
        containerWidth: "1280px",
        borderRadius: "rounded-2xl",
        buttonRadius: "rounded-xl",
        cardShadow: "subtle",
      },
      announcement: {
        enabled: true,
        text: "⚡ FRETE GRÁTIS para todo o Brasil acima de R$ 199 | Parcele em até 12x",
        badgeText: "NOVIDADE",
        linkText: "Aproveitar Agora",
        linkUrl: "/produtos",
        bgStyle: "dark",
        showSecurityBadge: true,
      },
      header: {
        sticky: true,
        logoText: "SensaShop",
        logoBadge: "Store",
        searchPlaceholder: "Buscar em todos os produtos...",
        showCartBadge: true,
        showAccountLink: true,
      },
      social: {
        instagram: "https://instagram.com",
        whatsapp: "https://whatsapp.com",
        tiktok: "https://tiktok.com",
      },
      footer: {
        copyright: "© 2026 SensaShop. Todos os direitos reservados.",
        tagline: "A sua experiência de compras completa inspirada no ecossistema Shopify.",
        showPaymentBadges: true,
        showNewsletter: true,
        columns: [
          {
            id: "col-1",
            title: "Categorias",
            links: [
              { label: "Eletrônicos", href: "/produtos?categoria=eletronicos" },
              { label: "Moda & Estilo", href: "/produtos?categoria=moda" },
              { label: "Casa & Decoração", href: "/produtos?categoria=casa-decoracao" },
            ],
          },
          {
            id: "col-2",
            title: "Atendimento",
            links: [
              { label: "Central de Ajuda", href: "#" },
              { label: "Rastrear Pedido", href: "/conta" },
              { label: "Trocas e Devoluções", href: "#" },
            ],
          },
        ],
      },
      customCss: "",
      sections: [
        {
          id: "sec-hero-1",
          type: "hero_banner",
          name: "Banner Principal (Hero)",
          enabled: true,
          settings: {
            eyebrow: "✨ Nova Coleção 2026 • Shopify Experience",
            title: "Os melhores produtos com a qualidade que você confia.",
            titleHighlight: "confia",
            subtitle: "Explore milhares de itens selecionados a dedo com entrega rápida e garantia total de 30 dias.",
            primaryButtonText: "Explorar Catálogo",
            primaryButtonUrl: "/produtos",
            secondaryButtonText: "Ver Novidades",
            secondaryButtonUrl: "/produtos?ordem=recentes",
            stat1Number: "+10k",
            stat1Label: "Pedidos Entregues",
            stat2Number: "4.9 ★",
            stat2Label: "Avaliação Média",
            stat3Number: "100%",
            stat3Label: "Checkout Seguro",
          },
        },
        {
          id: "sec-marquee-1",
          type: "marquee_ticker",
          name: "Faixa de Destaques (Marquee)",
          enabled: true,
          settings: {
            speed: "normal",
            bgColor: "#008060",
            textColor: "#ffffff",
            items: [
              "🚀 ENVIO RÁPIDO PARA TODO BRASIL",
              "🔒 PAGAMENTO 100% SEGURO",
              "💳 ATÉ 12X SEM JUROS",
              "⭐ MAIS DE 5.000 CLIENTES SATISFEITOS",
            ],
          },
        },
        {
          id: "sec-features-1",
          type: "features_bar",
          name: "Diferenciais da Loja",
          enabled: true,
          settings: {
            f1Title: "Frete Grátis",
            f1Desc: "Em compras acima de R$ 199 para todo o Brasil",
            f2Title: "Até 12x Sem Juros",
            f2Desc: "Ou 5% de desconto à vista via Pix",
            f3Title: "Compra Garantida",
            f3Desc: "30 dias para trocas e devoluções grátis",
            f4Title: "Suporte 24/7",
            f4Desc: "Atendimento humanizado em tempo real",
          },
        },
        {
          id: "sec-featured-products-1",
          type: "featured_products",
          name: "Produtos em Destaque",
          enabled: true,
          settings: {
            eyebrow: "Destaques da Loja",
            title: "Mais Vendidos da Semana",
            limit: 8,
            sort: "price_desc",
            categorySlug: "all",
          },
        },
        {
          id: "sec-promo-1",
          type: "promo_banner",
          name: "Banner Promocional",
          enabled: true,
          settings: {
            badge: "Promoção por Tempo Limitado ⚡",
            heading: "Até 40% OFF nos produtos mais desejados",
            description: "Use o cupom PRIMEIRACOMPRA no checkout para garantir 10% de desconto adicional.",
            couponCode: "PRIMEIRACOMPRA",
            buttonText: "Aproveitar Ofertas",
            buttonUrl: "/produtos",
            themeStyle: "dark",
          },
        },
        {
          id: "sec-faq-1",
          type: "faq_accordion",
          name: "Perguntas Frequentes (FAQ)",
          enabled: true,
          settings: {
            title: "Dúvidas Frequentes",
            subtitle: "Tudo o que você precisa saber antes de comprar",
          },
          blocks: [
            {
              id: "faq-1",
              type: "faq_item",
              settings: {
                question: "Qual o prazo de entrega dos pedidos?",
                answer: "O prazo varia de 2 a 7 dias úteis dependendo da sua região com rastreamento completo.",
              },
            },
            {
              id: "faq-2",
              type: "faq_item",
              settings: {
                question: "Como funciona a garantia de 30 dias?",
                answer: "Caso não goste ou queira trocar, garantimos a devolução 100% gratuita dentro de 30 dias.",
              },
            },
          ],
        },
        {
          id: "sec-newsletter-1",
          type: "newsletter",
          name: "Captura de E-mails (Newsletter)",
          enabled: true,
          settings: {
            heading: "Fique por dentro das ofertas exclusivas",
            text: "Cadastre seu e-mail e receba cupons de desconto VIP e lançamentos em primeira mão.",
            placeholder: "Digite seu melhor e-mail...",
            buttonText: "Cadastrar",
          },
        },
      ],
    },
  },
  {
    id: "sense",
    name: "Sense",
    badge: "Beleza & Cosméticos",
    description: "Tema vibrante e acolhedor em tons de rosa e ouro, botões em pílula e tipografia Poppins sofisticada.",
    primaryColor: "#e11d48",
    accentColor: "#f59e0b",
    config: {
      id: "sense",
      name: "Sense - Glow & Beauty",
      version: "15.0.0",
      updatedAt: new Date().toISOString(),
      colors: {
        primary: "#e11d48",
        primaryHover: "#be123c",
        accent: "#f59e0b",
        background: "#fff1f2",
        surface: "#ffffff",
        textMain: "#1f2937",
        textMuted: "#6b7280",
        border: "#fecdd3",
      },
      typography: {
        headingFont: "Poppins",
        bodyFont: "Inter",
        baseFontSize: "16px",
      },
      layout: {
        containerWidth: "1280px",
        borderRadius: "rounded-3xl",
        buttonRadius: "rounded-full",
        cardShadow: "glow",
      },
      announcement: {
        enabled: true,
        text: "🌸 SEMANA DO AUTOCUIDADO: Brindes exclusivos em compras acima de R$ 150",
        badgeText: "BELEZA",
        linkText: "Conferir Brindes",
        linkUrl: "/produtos",
        bgStyle: "brand",
        showSecurityBadge: true,
      },
      header: {
        sticky: true,
        logoText: "SenseGlow",
        logoBadge: "Beauty",
        searchPlaceholder: "Buscar maquiagens, skincare e fragrâncias...",
        showCartBadge: true,
        showAccountLink: true,
      },
      social: {
        instagram: "https://instagram.com",
        tiktok: "https://tiktok.com",
        whatsapp: "https://whatsapp.com",
      },
      footer: {
        copyright: "© 2026 SenseGlow Beauty. Realce sua beleza natural.",
        tagline: "Produtos dermatologicamente testados, veganos e cruelty-free.",
        showPaymentBadges: true,
        showNewsletter: true,
        columns: [
          {
            id: "col-1",
            title: "Linhas Especiais",
            links: [
              { label: "Skincare Facial", href: "/produtos" },
              { label: "Cuidados Corporais", href: "/produtos" },
              { label: "Fragrâncias & Óleos", href: "/produtos" },
            ],
          },
          {
            id: "col-2",
            title: "Ajuda & Dúvidas",
            links: [
              { label: "Guia de Tipos de Pele", href: "#" },
              { label: "Fale com a Dermato", href: "#" },
              { label: "Rastrear Meu Pedido", href: "/conta" },
            ],
          },
        ],
      },
      customCss: "",
      sections: [
        {
          id: "sec-hero-sense",
          type: "hero_banner",
          name: "Hero Glow & Beauty",
          enabled: true,
          settings: {
            eyebrow: "✨ Fórmulas Exclusivas & 100% Veganas",
            title: "Sinta o poder do autocuidado diário na sua pele.",
            titleHighlight: "autocuidado",
            subtitle: "Linhas dermatológicas desenvolvidas com ativos botânicos raros para nutrir, hidratar e iluminar.",
            primaryButtonText: "Ver Coleção Glow",
            primaryButtonUrl: "/produtos",
            secondaryButtonText: "Descubra Seu Tipo",
            secondaryButtonUrl: "/produtos",
            stat1Number: "+25k",
            stat1Label: "Mulheres Iluminadas",
            stat2Number: "5.0 ★",
            stat2Label: "Aprovado por Dermatos",
            stat3Number: "100%",
            stat3Label: "Vegano & Sem Testes",
          },
        },
        {
          id: "sec-features-sense",
          type: "features_bar",
          name: "Compromissos Sense",
          enabled: true,
          settings: {
            f1Title: "100% Cruelty-Free",
            f1Desc: "Nenhum ingrediente testado em animais",
            f2Title: "Fragrância Natural",
            f2Desc: "Óleos essenciais puros sem parabenos",
            f3Title: "Frete Grátis Express",
            f3Desc: "Entrega perfumada em todo o Brasil",
            f4Title: "Troca Sem Custo",
            f4Desc: "Satisfação total garantida por 30 dias",
          },
        },
        {
          id: "sec-featured-sense",
          type: "featured_products",
          name: "Queridinhos da Semana",
          enabled: true,
          settings: {
            eyebrow: "Mais Vendidos",
            title: "Os Mais Desejados para sua Rotina",
            limit: 8,
            sort: "price_desc",
            categorySlug: "all",
          },
        },
        {
          id: "sec-testimonials-sense",
          type: "testimonials",
          name: "Depoimentos de Quem Usa",
          enabled: true,
          settings: {
            title: "Amor à Primeira Aplicação",
            subtitle: "Veja a transformação na rotina de quem já experimentou",
          },
          blocks: [
            {
              id: "t-s1",
              type: "testimonial_item",
              settings: {
                author: "Juliana Paes",
                role: "São Paulo, SP",
                rating: 5,
                comment: "O Sérum Hidratante transformou minha pele em 7 dias! Textura leve, toque aveludado e cheiro divino.",
              },
            },
            {
              id: "t-s2",
              type: "testimonial_item",
              settings: {
                author: "Beatriz Ramos",
                role: "Rio de Janeiro, RJ",
                rating: 5,
                comment: "A embalagem é um espetáculo à parte e o produto dura muito. Já é minha terceira compra!",
              },
            },
          ],
        },
      ],
    },
  },
  {
    id: "craft",
    name: "Craft",
    badge: "Design Editorial & Luxo",
    description: "Estética refinada para decoração, moda e arquitetura com tons quentes de terracota e Playfair Display.",
    primaryColor: "#92400e",
    accentColor: "#d97706",
    config: {
      id: "craft",
      name: "Craft - Atelier & Home",
      version: "15.0.0",
      updatedAt: new Date().toISOString(),
      colors: {
        primary: "#92400e",
        primaryHover: "#78350f",
        accent: "#d97706",
        background: "#fafaf9",
        surface: "#ffffff",
        textMain: "#1c1917",
        textMuted: "#78716c",
        border: "#e7e5e4",
      },
      typography: {
        headingFont: "Playfair Display",
        bodyFont: "Inter",
        baseFontSize: "16px",
      },
      layout: {
        containerWidth: "1400px",
        borderRadius: "rounded-lg",
        buttonRadius: "rounded-lg",
        cardShadow: "subtle",
      },
      announcement: {
        enabled: true,
        text: "🏺 COLEÇÃO ATELIER 2026: Peças limitadas assinadas por designers renomados",
        badgeText: "EXCLUSIVO",
        linkText: "Ver Catálogo",
        linkUrl: "/produtos",
        bgStyle: "dark",
        showSecurityBadge: true,
      },
      header: {
        sticky: true,
        logoText: "Atelier Craft",
        logoBadge: "Maison",
        searchPlaceholder: "Pesquisar por autor, material ou coleção...",
        showCartBadge: true,
        showAccountLink: true,
      },
      social: {
        instagram: "https://instagram.com",
        facebook: "https://facebook.com",
      },
      footer: {
        copyright: "© 2026 Atelier Craft. Arte, design e autenticidade.",
        tagline: "Móveis e objetos de arte com matérias-primas nobres e acabamento impecável.",
        showPaymentBadges: true,
        showNewsletter: true,
        columns: [
          {
            id: "col-1",
            title: "Coleções",
            links: [
              { label: "Mobiliário Autoral", href: "/produtos" },
              { label: "Iluminação & Cerâmica", href: "/produtos" },
              { label: "Têxteis em Linho Puro", href: "/produtos" },
            ],
          },
        ],
      },
      customCss: "",
      sections: [
        {
          id: "sec-hero-craft",
          type: "hero_banner",
          name: "Hero Editorial Craft",
          enabled: true,
          settings: {
            eyebrow: "Edição Especial Limitada",
            title: "Design atemporal criado para transformar o seu espaço.",
            titleHighlight: "atemporal",
            subtitle: "Cada peça carrega a alma do artesanato contemporâneo combinada com materiais de alta sustentabilidade.",
            primaryButtonText: "Explorar Atelier",
            primaryButtonUrl: "/produtos",
            secondaryButtonText: "Conhecer Artesãos",
            secondaryButtonUrl: "/produtos",
            stat1Number: "100%",
            stat1Label: "Feito à Mão",
            stat2Number: "50 Anos",
            stat2Label: "Durabilidade da Madeira",
            stat3Number: "Selo FSC",
            stat3Label: "Origem Sustentável",
          },
        },
        {
          id: "sec-products-craft",
          type: "featured_products",
          name: "Destaques do Atelier",
          enabled: true,
          settings: {
            eyebrow: "Curadoria",
            title: "Peças em Evidência",
            limit: 4,
            sort: "price_desc",
            categorySlug: "all",
          },
        },
        {
          id: "sec-image-text-craft",
          type: "image_with_text",
          name: "História dos Materiais",
          enabled: true,
          settings: {
            badge: "Herança & Técnica",
            heading: "Tradição marceneira aliada à tecnologia de ponta",
            bodyText: "Resgatamos técnicas ancestrais de encaixe de madeira para criar móveis sólidos que dispensam parafusos aparentes.",
            buttonText: "Nossa Filosofia",
            buttonUrl: "/produtos",
            imagePosition: "left",
            item1: "Madeiras nobres certificadas",
            item2: "Verniz atóxico à base de água",
            item3: "Certificado de autenticidade numerado",
          },
        },
      ],
    },
  },
  {
    id: "origin",
    name: "Origin",
    badge: "Cyber & Streetwear",
    description: "Modo escuro com violeta elétrico e ciano neon, tipografia Outfit e energia moderna de streetwear.",
    primaryColor: "#7c3aed",
    accentColor: "#06b6d4",
    config: {
      id: "origin",
      name: "Origin - Cyber & Streetwear",
      version: "15.0.0",
      updatedAt: new Date().toISOString(),
      colors: {
        primary: "#7c3aed",
        primaryHover: "#6d28d9",
        accent: "#06b6d4",
        background: "#09090b",
        surface: "#18181b",
        textMain: "#f4f4f5",
        textMuted: "#a1a1aa",
        border: "#27272a",
      },
      typography: {
        headingFont: "Outfit",
        bodyFont: "Geist",
        baseFontSize: "16px",
      },
      layout: {
        containerWidth: "1280px",
        borderRadius: "rounded-2xl",
        buttonRadius: "rounded-xl",
        cardShadow: "glow",
      },
      announcement: {
        enabled: true,
        text: "⚡ DROP 04 LIBERADO: Envio imediato para todo o país com rastreio ao vivo",
        badgeText: "NOVO DROP",
        linkText: "Garantir Peça",
        linkUrl: "/produtos",
        bgStyle: "brand",
        showSecurityBadge: true,
      },
      header: {
        sticky: true,
        logoText: "ORIGIN",
        logoBadge: "LABS",
        searchPlaceholder: "Buscar por drop, modelo ou collab...",
        showCartBadge: true,
        showAccountLink: true,
      },
      social: {
        instagram: "https://instagram.com",
        tiktok: "https://tiktok.com",
        twitter: "https://x.com",
      },
      footer: {
        copyright: "© 2026 ORIGIN LABS. Engineered for the future.",
        tagline: "Streetwear tech, vestuário de alta performance e colaborações exclusivas.",
        showPaymentBadges: true,
        showNewsletter: true,
        columns: [
          {
            id: "col-1",
            title: "Drops Recentes",
            links: [
              { label: "Drop 04 - Cyberpunk", href: "/produtos" },
              { label: "Jaquetas & Corta-Ventos", href: "/produtos" },
              { label: "Acessórios & Bags", href: "/produtos" },
            ],
          },
        ],
      },
      customCss: "",
      sections: [
        {
          id: "sec-hero-origin",
          type: "hero_banner",
          name: "Hero Origin Cyber",
          enabled: true,
          settings: {
            eyebrow: "⚡ Engineered in 2026",
            title: "O futuro do streetwear urbano com tecnologia térmica.",
            titleHighlight: "streetwear",
            subtitle: "Tecidos hidrofóbicos, costuras reforçadas e cortes assimétricos inspirados na arquitetura futurista.",
            primaryButtonText: "Explorar Drop 04",
            primaryButtonUrl: "/produtos",
            secondaryButtonText: "Ver Lookbook",
            secondaryButtonUrl: "/produtos",
            stat1Number: "48 Horas",
            stat1Label: "Esgotamento Médio",
            stat2Number: "100%",
            stat2Label: "Resistente à Água",
            stat3Number: "+15k",
            stat3Label: "Membros da Comunidade",
          },
        },
        {
          id: "sec-marquee-origin",
          type: "marquee_ticker",
          name: "Marquee Neon",
          enabled: true,
          settings: {
            speed: "normal",
            bgColor: "#7c3aed",
            textColor: "#ffffff",
            items: [
              "⚡ NOVO DROP ONLINE",
              "🔥 ESTOQUE ULTRA LIMITADO",
              "🚀 ENTREGA EXPRESSA",
              "🔒 CHECKOUT CRIPTOGRAFADO",
            ],
          },
        },
        {
          id: "sec-products-origin",
          type: "featured_products",
          name: "Destaques do Drop",
          enabled: true,
          settings: {
            eyebrow: "Drop Ativo",
            title: "Peças em Alta na Comunidade",
            limit: 8,
            sort: "price_desc",
            categorySlug: "all",
          },
        },
      ],
    },
  },
  {
    id: "studio",
    name: "Studio",
    badge: "Monochrome & Tangerine",
    description: "Design minimalista contemporâneo de alto contraste em preto absoluto e laranja elétrico.",
    primaryColor: "#f97316",
    accentColor: "#fbbf24",
    config: {
      id: "studio",
      name: "Studio - Bold Minimal",
      version: "15.0.0",
      updatedAt: new Date().toISOString(),
      colors: {
        primary: "#f97316",
        primaryHover: "#ea580c",
        accent: "#fbbf24",
        background: "#ffffff",
        surface: "#f8fafc",
        textMain: "#0f172a",
        textMuted: "#64748b",
        border: "#e2e8f0",
      },
      typography: {
        headingFont: "Inter",
        bodyFont: "Inter",
        baseFontSize: "16px",
      },
      layout: {
        containerWidth: "1280px",
        borderRadius: "rounded-xl",
        buttonRadius: "rounded-lg",
        cardShadow: "subtle",
      },
      announcement: {
        enabled: true,
        text: "⚡ STUDIO SALE: Compre 2 itens e ganhe 20% OFF no carrinho",
        badgeText: "OFERTA",
        linkText: "Ver Seleção",
        linkUrl: "/produtos",
        bgStyle: "brand",
        showSecurityBadge: true,
      },
      header: {
        sticky: true,
        logoText: "STUDIO",
        logoBadge: "LAB",
        searchPlaceholder: "Buscar produtos do Studio...",
        showCartBadge: true,
        showAccountLink: true,
      },
      social: {
        instagram: "https://instagram.com",
        tiktok: "https://tiktok.com",
      },
      footer: {
        copyright: "© 2026 Studio. Minimalismo funcional.",
        tagline: "Menos ruído, mais impacto. Produtos criados para o cotidiano.",
        showPaymentBadges: true,
        showNewsletter: true,
        columns: [
          {
            id: "col-1",
            title: "Produtos",
            links: [
              { label: "Novidades", href: "/produtos" },
              { label: "Mais Vendidos", href: "/produtos" },
            ],
          },
        ],
      },
      customCss: "",
      sections: [
        {
          id: "sec-hero-studio",
          type: "hero_banner",
          name: "Hero Minimalista Studio",
          enabled: true,
          settings: {
            eyebrow: "Design Puro & Funcional",
            title: "O essencial elevado ao máximo de excelência.",
            titleHighlight: "excelência",
            subtitle: "Criamos objetos pensados para quem valoriza clareza visual, ergonomia e durabilidade extrema.",
            primaryButtonText: "Comprar Agora",
            primaryButtonUrl: "/produtos",
            secondaryButtonText: "Ver Vídeo",
            secondaryButtonUrl: "/produtos",
            stat1Number: "100%",
            stat1Label: "Design Autoral",
            stat2Number: "4.9 ★",
            stat2Label: "Review Global",
            stat3Number: "Zero",
            stat3Label: "Desperdício Plástico",
          },
        },
        {
          id: "sec-products-studio",
          type: "featured_products",
          name: "Catálogo Essencial",
          enabled: true,
          settings: {
            eyebrow: "Destaques",
            title: "Itens Mais Desejados",
            limit: 8,
            sort: "price_desc",
            categorySlug: "all",
          },
        },
      ],
    },
  },
];
